# Numpy and Ndarrays

In [1]:
import numpy as np

In [2]:
l1 = [1, 2, 3]
x = np.array(l1, dtype=np.int16)

In [3]:
x = np.array([1, 2, 3], dtype=np.int16)

In [5]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


# Indexing in Ndarrays

In [7]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [8]:
print(x[-1])

3


In [10]:
# print(x[3]) # IndexError

## Indexing in Ndarrays of More Than One Dimension

In [11]:
x1 = np.array([[1, 2, 3], [4, 5, 6]], np.int16)

In [13]:
print(x1[0, 0]); print(x1[0, 1]); print(x1[0, 2])

1
2
3


In [23]:
# access entire rows
print(x1[0, :])
print(x1[1, :])

[1 2 3]
[4 5 6]


In [22]:
# access entire columns
print(x1[:, 0])

[1 4]


In [24]:
x2 = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16)

In [25]:
print(x2[0, 0, 0])

1


In [27]:
print(x2[1, 1, 2])

-5


In [35]:
print(x2[:, 1, 1])

[ 5 -4]


# Ndarray Properties

In [36]:
x2 = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16)

In [37]:
print(x2.ndim)

3


In [39]:
print(x2.shape)

(2, 2, 3)


In [41]:
print(x2.dtype)

int16


In [44]:
print(x2.size)
print(x2.nbytes)

12
24


In [45]:
print(x2.T)

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


# NumPy Constants

In [46]:
print(np.inf)

inf


In [47]:
print(np.NAN)

nan


In [48]:
print(np.NINF)

-inf


In [50]:
print(np.NZERO)
print(np.PZERO)

-0.0
0.0


In [51]:
print(np.e)

2.718281828459045


In [53]:
print(np.euler_gamma)
print(np.pi)

0.5772156649015329
3.141592653589793


# Slicing Ndarrays

In [54]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7])
a1[1:5]

array([2, 3, 4, 5])

In [55]:
a1[3:]

array([4, 5, 6, 7])

In [56]:
a1[:3]

array([1, 2, 3])

In [57]:
a1[-4:-1]

array([4, 5, 6])

In [58]:
a1[1:6:2]

array([2, 4, 6])